name: Deploy to Server

on:
  push:
    branches:
      - main # branch de produção

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to server
        run: |
          rsync -avz --delete ./ root@srv948114.hstgr.cloud:/var/www/br7site/

      - name: Restart Gunicorn
        run: ssh root@srv948114.hstgr.cloud 'sudo systemctl restart gunicorn'
